name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/setup-node@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Use Node.js V16
           uses: actions/setup-node@v3
           with:
              node-version: "16.14.2"

      - name: Cypress run
        uses: cypress-io/github-action@v4
           with:
              config-file: cypress.config.js
              browser: chrome
              headed: true
          start: npm run test
