name: Cypress Tests

on: [push]
branches:
  - main
  - QA

jobs:
  cypress-run:
    runs-on: windows2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
          with:
              config-file: cypress.config.js
              browser: chrome
              headed: true

               name: Generate Report
           if: always()
           run: npm run testreport

            name: Save Report
           if: always()
           uses: actions/upload-artifact@v3
           with:
              name: Final Report
              path: report/

              - name: Download all workflow run artifacts
           if: always()
           uses: actions/download-artifact@v3
