name: Cypress Tests

on:
  push:
    branches:
      - main
      - QA
  pull_request:
    branches: 
     - main

jobs:
  Cypress-v10-run-tests-windows:
    runs-on: ${{ matrix.os }}
    matrix:
        node-version: "16.14.2"
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      # install a specific version of Node using
      - name: Use Node.js V16
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.python-version }}

      # install and Run Cypress
      - name: Running cypress V10
        id: runningcypress
        uses: cypress-io/github-action@v4
        with:
          config-file: cypress.config.js
          browser: chrome
          headed: true

       

