name: Cypress Tests

on:
  push:
    branches:
      - main
      - QA

jobs:
  Cypress-run-tests:
    matrix: version: [10, 12, 14]
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      # install a specific version of Node using
      - name: Use Node.js V16
        uses: actions/setup-node@v3
        with:
          node-version: "16.16.0"

      # install and Run Cypress
      - name: Running cypress V10
        uses: cypress-io/github-action@v4
        with:
          config-file: cypress.config.js
          browser: chrome
          headed: true
